steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/election-iq'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY'
      - '--build-arg'
      - 'VITE_MAPS_API_KEY=$_VITE_MAPS_API_KEY'
      - '--build-arg'
      - 'VITE_YOUTUBE_API_KEY=$_VITE_YOUTUBE_API_KEY'
      - '--build-arg'
      - 'VITE_TTS_API_KEY=$_VITE_TTS_API_KEY'
      - '--build-arg'
      - 'VITE_TRANSLATE_API_KEY=$_VITE_TRANSLATE_API_KEY'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/election-iq'
